# .gitpod.yml
image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # Start Xvfb in the background
      Xvfb :99 -screen 0 1024x768x16 &
      export DISPLAY=:99
      # Install dependencies and set up the environment
      sudo apt-get update
      sudo apt-get install -y cmake
    command: |
      # Commands to run your project
      cmake .
      make
      ./your_native_ui_program

vscode:
  extensions:
    - ms-vscode.cpptools
    - ms-python.python
    - ms-python.vscode-pylance
